spring:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: word-snake

    properties:
      schema.registry.url: "http://localhost:8081"

    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
      group-id: ${random.uuid}
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

application:
  streams-config:
    application-id: word-snake
    words-to-eliminate: \,:\.
    input-path-file: C:\Users\lamtuad\Documents\kafka-streams-word-snake\input_sentences.txt
    schema-registry-url: http://localhost:8081
    input-topic: raw_input_topic
    output-processed-topic: output_snake_topic
    output-file-path: C:\Users\lamtuad\Documents\kafka-streams-word-snake\output.txt
