spring:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: word-snake

    properties:
      schema.registry.url: "http://localhost:8081"

    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

application:
  streams-config:
    application-id: word-snake
    words-to-eliminate: \,
    input-path-file: C:\Users\lamtuad\Documents\kafka-streams-word-snake\src\main\resources\input_sentences.txt
    input-topic: raw_input_topic
    output-raw-topic: output_raw
    output-processed-topic: output_processed
    invalid-topic: invalid_topic